In [1]:
# 시리즈연산
# Series객체 + 연산자(+, -, *, /) + 숫자(스칼라)

import pandas as pd

dict_data = {
    "국어": 100,
    "영어": 80,
    "수학": 90
}

student1 = pd.Series(dict_data)
student1

국어    100
영어     80
수학     90
dtype: int64

In [2]:
persentage = student1/100

print(persentage)
print(type(persentage))

국어    1.0
영어    0.8
수학    0.9
dtype: float64
<class 'pandas.Series'>

In [4]:
# 시리즈 vs 시리즈
# Series + 연산자(+, -, *, /) + Series2

student2 = pd.Series({"수학": 80,"국어": 90, "영어": 80})

print(student1)
print()
print(student2)

국어    100
영어     80
수학     90
dtype: int64

수학    80
국어    90
영어    80
dtype: int64

In [5]:
addition = student1 + student2
addition

국어    190
수학    170
영어    160
dtype: int64

In [6]:
subraction = student1 - student2
subraction

국어    10
수학    10
영어     0
dtype: int64

In [8]:
multplication = student1 * student2
multplication

국어    9000
수학    7200
영어    6400
dtype: int64

In [13]:
division = student1 / student2
division

국어    1.111111
수학    1.125000
영어    1.000000
dtype: float64

In [14]:
result = pd.DataFrame([addition, subraction, multplication, division],
                      index=["덧셈", "뺄셈", "곱셈", "나눗셈"])

result

              국어        수학      영어
덧셈    190.000000   170.000   160.0
뺄셈     10.000000    10.000     0.0
곱셈   9000.000000  7200.000  6400.0
나눗셈     1.111111     1.125     1.0

In [16]:
# NaN 값이 있는 시리즈 연산

import pandas as pd
import numpy as np

student1 = pd.Series({"국어":np.nan, "영어":80, "수학":90})
student2 = pd.Series({"수학":80, "국어": 30})

print(student1)
print()
print(student2)

국어     NaN
영어    80.0
수학    90.0
dtype: float64

수학    80
국어    30
dtype: int64

In [18]:
addition = student1 + student2
subraction = student1 - student2
multplication = student1 * student2
division = student1 / student2

print(addition)
print(subraction)
print(multplication)
print(division)

국어      NaN
수학    170.0
영어      NaN
dtype: float64
국어     NaN
수학    10.0
영어     NaN
dtype: float64
국어       NaN
수학    7200.0
영어       NaN
dtype: float64
국어      NaN
수학    1.125
영어      NaN
dtype: float64

In [19]:
result = pd.DataFrame([addition, subraction, multplication, division],
                      index=["덧셈", "뺄셈", "곱셈", "나눗셈"])

result

     국어        수학  영어
덧셈  NaN   170.000 NaN
뺄셈  NaN    10.000 NaN
곱셈  NaN  7200.000 NaN
나눗셈 NaN     1.125 NaN