In [80]:
import pandas as pd

df = pd.read_csv("./data/stock-data.csv")

df.head()

         Date  Close  Start   High    Low  Volume
0  2018-07-02  10100  10850  10900  10000  137977
1  2018-06-29  10700  10550  10900   9990  170253
2  2018-06-28  10400  10900  10950  10150  155769
3  2018-06-27  10900  10800  11050  10500  133548
4  2018-06-26  10800  10900  11000  10700   63039

In [81]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    20 non-null     str
 1   Close   20 non-null     int64
 2   Start   20 non-null     int64
 3   High    20 non-null     int64
 4   Low     20 non-null     int64
 5   Volume  20 non-null     int64
dtypes: int64(5), str(1)
memory usage: 1.1 KB

In [82]:
df.isnull().sum()

Date      0
Close     0
Start     0
High      0
Low       0
Volume    0
dtype: int64

In [83]:
df["new_date"] = pd.to_datetime(df["Date"])
df.head()

         Date  Close  Start   High    Low  Volume   new_date
0  2018-07-02  10100  10850  10900  10000  137977 2018-07-02
1  2018-06-29  10700  10550  10900   9990  170253 2018-06-29
2  2018-06-28  10400  10900  10950  10150  155769 2018-06-28
3  2018-06-27  10900  10800  11050  10500  133548 2018-06-27
4  2018-06-26  10800  10900  11000  10700   63039 2018-06-26

In [84]:
df = df.set_index("new_date")
df = df.drop("Date", axis=1)

df.head()

            Close  Start   High    Low  Volume
new_date
2018-07-02  10100  10850  10900  10000  137977
2018-06-29  10700  10550  10900   9990  170253
2018-06-28  10400  10900  10950  10150  155769
2018-06-27  10900  10800  11050  10500  133548
2018-06-26  10800  10900  11000  10700   63039

In [85]:
pd.DatetimeIndex([
    "2022-12-12", "2023/01/25"
])

DatetimeIndex(['2022-12-12', '2023-01-25'], dtype='datetime64[us]', freq=None)

In [86]:
pd.Timestamp("2023-12-25")

Timestamp('2023-12-25 00:00:00')

In [87]:
pd.Timestamp("2023/12/25")

Timestamp('2023-12-25 00:00:00')

In [88]:
pd.to_datetime("2025/12/25")

Timestamp('2025-12-25 00:00:00')

In [89]:
pd.to_datetime("2025년 12월 25일", format="%Y년 %m월 %d일")

Timestamp('2025-12-25 00:00:00')

In [90]:
pd.to_datetime("12-12-2023 23:59:59", format="%d-%m-%Y %H:%M:%S")

Timestamp('2023-12-12 23:59:59')

In [91]:
# Timestamp를 이용해서 period로 변환

dates = ["2019-01-01", "2020-03-01", "2021-06-01"]

ts_dates = pd.to_datetime(dates)
ts_dates

DatetimeIndex(['2019-01-01', '2020-03-01', '2021-06-01'], dtype='datetime64[us]', freq=None)

In [92]:
pr_day = ts_dates.to_period(freq="D")
pr_day

PeriodIndex(['2019-01-01', '2020-03-01', '2021-06-01'], dtype='period[D]')

In [93]:
pr_month = ts_dates.to_period(freq="M")
pr_month

PeriodIndex(['2019-01', '2020-03', '2021-06'], dtype='period[M]')

In [94]:
pr_year = ts_dates.to_period(freq="Y")
pr_year

PeriodIndex(['2019', '2020', '2021'], dtype='period[Y-DEC]')

In [95]:
# 시계열 데이터 만들기

ts_ms = pd.date_range(
    start="2024-01-01",
    end=None,
    periods=6,
    freq="MS",
    tz="Asia/Seoul"
)

ts_ms

DatetimeIndex(['2024-01-01 00:00:00+09:00', '2024-02-01 00:00:00+09:00',
               '2024-03-01 00:00:00+09:00', '2024-04-01 00:00:00+09:00',
               '2024-05-01 00:00:00+09:00', '2024-06-01 00:00:00+09:00'],
              dtype='datetime64[us, Asia/Seoul]', freq='MS')

In [96]:
ts_ms = pd.date_range(
    start="2024-01-01",
    periods=6,
    freq="ME",
    tz="Asia/Seoul"
)

ts_ms

DatetimeIndex(['2024-01-31 00:00:00+09:00', '2024-02-29 00:00:00+09:00',
               '2024-03-31 00:00:00+09:00', '2024-04-30 00:00:00+09:00',
               '2024-05-31 00:00:00+09:00', '2024-06-30 00:00:00+09:00'],
              dtype='datetime64[us, Asia/Seoul]', freq='ME')

In [97]:
ts_3m = pd.date_range(
    "2024-01-01",
    periods=6,
    freq="3MS",
    tz="Asia/Seoul"
)

ts_3m

DatetimeIndex(['2024-01-01 00:00:00+09:00', '2024-04-01 00:00:00+09:00',
               '2024-07-01 00:00:00+09:00', '2024-10-01 00:00:00+09:00',
               '2025-01-01 00:00:00+09:00', '2025-04-01 00:00:00+09:00'],
              dtype='datetime64[us, Asia/Seoul]', freq='3MS')

In [98]:
# 시계열 데이터 활용

df = pd.read_csv("./data/stock-data.csv")

df.head()

         Date  Close  Start   High    Low  Volume
0  2018-07-02  10100  10850  10900  10000  137977
1  2018-06-29  10700  10550  10900   9990  170253
2  2018-06-28  10400  10900  10950  10150  155769
3  2018-06-27  10900  10800  11050  10500  133548
4  2018-06-26  10800  10900  11000  10700   63039

In [99]:
df["new_Date"] = pd.to_datetime(df["Date"])
df.head()

         Date  Close  Start   High    Low  Volume   new_Date
0  2018-07-02  10100  10850  10900  10000  137977 2018-07-02
1  2018-06-29  10700  10550  10900   9990  170253 2018-06-29
2  2018-06-28  10400  10900  10950  10150  155769 2018-06-28
3  2018-06-27  10900  10800  11050  10500  133548 2018-06-27
4  2018-06-26  10800  10900  11000  10700   63039 2018-06-26

In [100]:
df["year"] = df["new_Date"].dt.year

In [101]:
df["Month"] = df["new_Date"].dt.month

In [102]:
df["day"] = df["new_Date"].dt.day

In [103]:
df.head()

         Date  Close  Start   High    Low  Volume   new_Date  year  Month  day
0  2018-07-02  10100  10850  10900  10000  137977 2018-07-02  2018      7    2
1  2018-06-29  10700  10550  10900   9990  170253 2018-06-29  2018      6   29
2  2018-06-28  10400  10900  10950  10150  155769 2018-06-28  2018      6   28
3  2018-06-27  10900  10800  11050  10500  133548 2018-06-27  2018      6   27
4  2018-06-26  10800  10900  11000  10700   63039 2018-06-26  2018      6   26

In [106]:
df["Date_yr"] = df["new_Date"].dt.to_period(freq="Y")

In [105]:
df["Date_m"] = df["new_Date"].dt.to_period(freq="M")

In [107]:
df.head()

,Date,Close,Start,High,Low,Volume,new_Date,year,Month,day,Date_m,Date_yr
0,2018-07-02,10100,10850,10900,10000,137977,2018-07-02,2018,7,2,2018-07,2018
1,2018-06-29,10700,10550,10900,9990,170253,2018-06-29,2018,6,29,2018-06,2018
2,2018-06-28,10400,10900,10950,10150,155769,2018-06-28,2018,6,28,2018-06,2018
3,2018-06-27,10900,10800,11050,10500,133548,2018-06-27,2018,6,27,2018-06,2018
4,2018-06-26,10800,10900,11000,10700,63039,2018-06-26,2018,6,26,2018-06,2018

In [109]:
# 시간인덱스 활용

df = pd.read_csv("./data/stock-data.csv")

df["new_Date"] = pd.to_datetime(df["Date"])
df.head()

         Date  Close  Start   High    Low  Volume   new_Date
0  2018-07-02  10100  10850  10900  10000  137977 2018-07-02
1  2018-06-29  10700  10550  10900   9990  170253 2018-06-29
2  2018-06-28  10400  10900  10950  10150  155769 2018-06-28
3  2018-06-27  10900  10800  11050  10500  133548 2018-06-27
4  2018-06-26  10800  10900  11000  10700   63039 2018-06-26

In [110]:
df = df.set_index("new_Date")

df.head()

                  Date  Close  Start   High    Low  Volume
new_Date
2018-07-02  2018-07-02  10100  10850  10900  10000  137977
2018-06-29  2018-06-29  10700  10550  10900   9990  170253
2018-06-28  2018-06-28  10400  10900  10950  10150  155769
2018-06-27  2018-06-27  10900  10800  11050  10500  133548
2018-06-26  2018-06-26  10800  10900  11000  10700   63039

In [113]:
df = df.sort_index() # sort_valeus()
df.head()

                  Date  Close  Start   High    Low  Volume
new_Date
2018-06-01  2018-06-01  11900  11800  12100  11750   32062
2018-06-04  2018-06-04  11900  11900  12200  11700   25171
2018-06-05  2018-06-05  12150  11800  12250  11800   42485
2018-06-07  2018-06-07  11950  12200  12300  11900   49088
2018-06-08  2018-06-08  11950  11950  12200  11800   59258

In [114]:
df.loc["2018-06-27"]

Date      2018-06-27
Close          10900
Start          10800
High           11050
Low            10500
Volume        133548
Name: 2018-06-27 00:00:00, dtype: object

In [115]:
df.loc["2018-06-27":"2018-07-02"]

                  Date  Close  Start   High    Low  Volume
new_Date
2018-06-27  2018-06-27  10900  10800  11050  10500  133548
2018-06-28  2018-06-28  10400  10900  10950  10150  155769
2018-06-29  2018-06-29  10700  10550  10900   9990  170253
2018-07-02  2018-07-02  10100  10850  10900  10000  137977

In [116]:
cond = df.index < "2018-06-05"
cond

array([ True,  True, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False])

In [119]:
df[cond]

                  Date  Close  Start   High    Low  Volume
new_Date
2018-06-01  2018-06-01  11900  11800  12100  11750   32062
2018-06-04  2018-06-04  11900  11900  12200  11700   25171

In [120]:
pd.Timestamp("2018-06-27")

Timestamp('2018-06-27 00:00:00')

In [121]:
pd.Timestamp(2018, 6, 27)

Timestamp('2018-06-27 00:00:00')

In [122]:
df.loc[pd.Timestamp(2018, 6, 27):pd.Timestamp(2018, 7, 2)]

                  Date  Close  Start   High    Low  Volume
new_Date
2018-06-27  2018-06-27  10900  10800  11050  10500  133548
2018-06-28  2018-06-28  10400  10900  10950  10150  155769
2018-06-29  2018-06-29  10700  10550  10900   9990  170253
2018-07-02  2018-07-02  10100  10850  10900  10000  137977

In [124]:
df.loc[pd.Timestamp(2018, 6, 27, 10, 30, 0):pd.Timestamp(2018, 7, 2, 23, 59, 59)]

                  Date  Close  Start   High    Low  Volume
new_Date
2018-06-28  2018-06-28  10400  10900  10950  10150  155769
2018-06-29  2018-06-29  10700  10550  10900   9990  170253
2018-07-02  2018-07-02  10100  10850  10900  10000  137977